#!/bin/bash
#script shell que calcula los votos del plebiscito
#
si=0
no=0
opcion=0
while true
do
  echo " "
  echo " "
  echo " "
  echo "           Republica De Colombia"
  echo "                 Pebliscito"
  echo " "
  echo "            Opciones"
  echo "            1. Voto Si"
  echo "            2. Voto No"
  echo "            3. Reslutados"
  echo "            4. Salir"
  echo " "
  echo " Digite opcion deseada...\c"
  read opcion
  case $opcion in
  1) si=`expr $si "+" 1`;;
  2) no=`expr $no "+" 1`;;
  3) echo "Resultados: "
     echo "Si = $si"
     echo "No = $no";;
  4) exit;;
  *) echo "Opcion invalida. Digite de nuevo"
    read nulo;;
esac
done
